name: CI
on: push
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          env:
           MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          run: echo "Deploying"
